; This file for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env4,@env0 ; 00 : Instrument 1

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$c4,$c7,$00,$00
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $01, $ff, $ed, $08
@song0ref10:
	.byte $cd, $47, $01, $ff, $ed, $08, $cd, $47, $01, $ff, $ed, $08, $cd
@song0ref23:
	.byte $47, $01, $ff, $ed, $08, $cd, $47, $06, $ff, $9d, $04, $cd, $02
	.byte $41, $10
	.word @song0ref10
	.byte $41, $0b
	.word @song0ref23
	.byte $cd
@song0ref43:
	.byte $47, $0d, $ff, $ed, $12, $cd, $47, $10, $ff, $9d, $15, $ff, $9d
	.byte $41, $0b
	.word @song0ref43
@song0ref59:
	.byte $47, $28, $91, $00, $91, $25, $91, $00, $91, $28, $91, $00, $91, $25, $91, $00, $91, $28, $91, $00, $91, $25, $91, $2c
	.byte $91, $2a, $91, $28, $91, $25, $91, $2a, $91
	.byte $41, $20
	.word @song0ref59
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ff, $bf, $80
@song0ref103:
	.byte $0d, $ff, $ed, $14, $cd, $0d, $ff, $ed, $14, $cd, $0d, $ff, $ed, $14, $cd, $1e, $ff, $9d, $1c, $cd, $1a, $cd, $00, $ff
	.byte $ff, $bd
	.byte $41, $16
	.word @song0ref103
@song0ref132:
	.byte $01, $ff, $ed, $06, $cd, $04, $ff, $9d, $09, $ff, $9d
	.byte $41, $0b
	.word @song0ref132
	.byte $01, $ff, $ed, $06, $cd, $1c, $91, $00, $91, $19, $91, $00, $91, $1c, $91, $00, $91, $19, $91, $00, $91, $1c, $91, $00
	.byte $91, $19, $91, $20, $91, $1e, $91, $1c, $91, $19, $91, $1e, $91, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $80
@song0ref194:
	.byte $19, $91, $1c, $91, $1e, $91, $1c, $91, $19, $91, $1c, $91, $1e, $91, $1c, $91, $1e, $91, $21, $91, $25, $91, $21, $91
	.byte $1e, $91, $21, $91, $28, $91, $27, $91
	.byte $41, $20
	.word @song0ref194
	.byte $00, $ff, $ff, $bd, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $20
	.word @song0ref194
	.byte $41, $20
	.word @song0ref194
	.byte $00, $ff, $ff, $bd, $31, $91, $00, $91, $2f
@song0ref254:
	.byte $91, $00, $91, $31, $91, $00, $91, $2f, $91, $00, $91, $31, $91
@song0ref267:
	.byte $00, $91, $2f, $91, $00, $91, $31, $91, $2f, $91, $31
	.byte $41, $15
	.word @song0ref254
	.byte $41, $0b
	.word @song0ref267
	.byte $91, $00
@song0ref286:
	.byte $91, $34, $91, $00, $91, $31, $91, $00, $91, $34, $91, $00, $91, $31, $91, $00, $91, $34, $91, $00, $91, $31, $91, $38
	.byte $91, $36, $91, $34, $91, $31, $91, $36
	.byte $41, $20
	.word @song0ref286
	.byte $41, $20
	.word @song0ref286
	.byte $41, $20
	.word @song0ref286
	.byte $91, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref332:
	.byte $ff
@song0ref333:
	.byte $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f, $80
@song0ref347:
	.byte $40, $50, $87, $00, $87, $40, $50, $87, $00, $87, $40, $50, $87, $00, $87, $40, $50, $87, $00, $87, $3a, $87, $00, $87
	.byte $3a, $87, $00, $87, $3a, $87, $00, $87, $3a, $87, $00, $87, $ff, $ff, $bf
@song0ref386:
	.byte $40, $51
@song0ref388:
	.byte $91, $40, $52, $91, $00, $91, $40, $52, $91, $00, $91, $40, $52, $91, $00
	.byte $41, $0c
	.word @song0ref388
	.byte $91, $40, $52, $91, $00, $a5
	.byte $41, $0d
	.word @song0ref386
	.byte $41, $0c
	.word @song0ref388
	.byte $91, $40, $52, $91, $00, $a5
	.byte $41, $0d
	.word @song0ref386
	.byte $41, $0c
	.word @song0ref388
	.byte $91, $40, $52, $91, $00, $a5, $ff, $9f
	.byte $41, $23
	.word @song0ref347
	.byte $41, $0d
	.word @song0ref332
	.byte $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0d
	.word @song0ref332
	.byte $41, $0c
	.word @song0ref333
	.byte $41, $0c
	.word @song0ref333
	.byte $41, $0b
	.word @song0ref333
	.byte $42
	.word @song0ch4loop
